// <auto-generated />
namespace MyOdeToFood.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddingBlobVarBinary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingBlobVarBinary));
        
        string IMigrationMetadata.Id
        {
            get { return "202006081229472_Adding Blob Var Binary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
